### ISSUE TITLE
Installation not working? Also Discord invite seems to be expired?

### ISSUE THREAD

**Issue by lilliandrift** [vlc-rpc/vlc-discord-rpc#17]
Hi! Just came across this and wanted to give it a go, though I seem to be having issues. using command 'npm i' works just fine but running up 'node . ' gives me an error message, claims that 'storage/config.js' can't be found. I was curious on if this was a bug or not. I made sure to run everything up correctly and double checked my steps. 

![Screenshot_1](https://github.com/vlc-rpc/vlc-discord-rpc/assets/107520567/38329dec-4c1a-4a2b-95c0-aa63016e818c)

I wanted to add as well that the support discord invite link expired and doesn't seem to be working.

**Comment by Lauren1066** [comment]
Hi, sorry about both issues. Copy the example config in the storage directory and make a config.js, then fill out the needed info. I will update the discord link the next time I am at a computer. 

https://discord.gg/CsKzGpt82s
