### ISSUE TITLE
Run VLC as detached

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [vlc-rpc/vlc-discord-rpc#3]
In Pigpog's original repo, there was a way to set up VLC to run ["detached" from vlc-discord-rpc](https://github.com/Pigpog/vlc-discord-rpc/blob/master/ADVANCED.md#detached-mode-best-experience:~:text=Out%20of%20the,a%20rich%20presence.):

> Out of the box, starting vlc-discord-rpc will open VLC, and closing VLC will close vlc-discord-rpc. This is the "attached" mode, and it is the default because "it just works" in most cases.
> 
> Detached mode will not open VLC for you, and closing VLC won't close vlc-discord-rpc. It requires a bit of tweaking, but once it is configured, it allows you to open and close VLC as you normally would and still show a rich presence.

How can we achieve this same functionality using your fork of vlc-discord-rpc?

**Comment by Lauren1066** [comment]
Fixed in https://github.com/vlc-rpc/vlc-discord-rpc/pull/7

Apologies for the wait.
