### ISSUE TITLE
Can't seem to get the movie icons to work

### ISSUE THREAD

**Issue by Patatjesneef** [vlc-rpc/vlc-discord-rpc#32]
I thought i'd try to get the movie icons to work, got my OMDb api key. The settings seem correct, but I think i just dont understand how to name the movies and where to put them. Can someone help?

**Comment by spix18** [comment]
whats your original movie name ? we made it so you dont have to rename your movie or show, if you find hard you can still use the manual script which you have to give the file path and movie or show name.

**Comment by Patatjesneef** [comment]
Guardians.Of.The.Galaxy.Vol.3 This is how most of my movies are named, they are all stored in E:\Movies and I tried to put the config to that directory but it doesn't seem to work

**Comment by Lauren1066** [comment]
Hello,
Did you try running the metadata scripts?

https://vlc-rpc.storinate.com/shows-and-movies.html

**Comment by Patatjesneef** [comment]
I have tried to, set the config to what i am using and made sure the names were correct but nothing seems to be happening?

**Comment by Patatjesneef** [comment]
I have figured it out, it seems that i didn't add ffmpeg to path correctly and that i needed to get the movies out of their respective folders and just put them in the directory. Thank you for your help
