### ISSUE TITLE
Fatal error when media name is less than 2 characters long

### ISSUE THREAD

**Issue by ynot01** [vlc-rpc/vlc-discord-rpc#34]
`Error: child "activity" fails because [child "details" fails because ["details" length must be at least 2 characters long]]`

**Comment by spix18** [comment]
can you provide more details of when this error is happening and what did u do exactly?
please don't just copy and paste the error.

**Comment by ynot01** [comment]
> can you provide more details of when this error is happening and what did u do exactly? please don't just copy and paste the error.

As is detailed in the error, this occurs because the `details` field in Discord RPC does not accept entries unless they are "at least 2 characters long"

The problem arises when media titles are only 1 character long and vlc-discord-rpc tries to relay the title in the `details` field

Examples of media with single character titles that would trigger this error:

[E by Fauna](https://www.youtube.com/watch?v=4cm0mQkkoQM)
[H by Böhse Onkelz](https://www.youtube.com/watch?v=4XpLaHXlzsY)
[D by Codeine](https://www.youtube.com/watch?v=PmSPPYG9dp4)
[V by Constructus Corporation](https://www.youtube.com/watch?v=CLDx-KlIi2A)
[K by Aidan Baker](https://www.youtube.com/watch?v=UJox1CKJgB8)
[K by Cul De Sac](https://www.youtube.com/watch?v=GSK8Uz-7vwo)
[U by Akufen](https://www.youtube.com/watch?v=YbfHVDTZn0o)
[X by Bailter Space](https://www.youtube.com/watch?v=zptnrC_ygtU)
[E by Cloakroom](https://www.youtube.com/watch?v=FScQCHUqN9E)
[M by The Cure](https://www.youtube.com/watch?v=h2HhnQxI8VI)

This is where the title of media is copied to `details`
https://github.com/vlc-rpc/vlc-discord-rpc/blob/125060006d5baf6b594c71d750a42e453d5a14b7/Functions/rpc-format.js#L55
https://github.com/vlc-rpc/vlc-discord-rpc/blob/125060006d5baf6b594c71d750a42e453d5a14b7/Functions/rpc-format.js#L75
https://github.com/vlc-rpc/vlc-discord-rpc/blob/125060006d5baf6b594c71d750a42e453d5a14b7/Functions/rpc-format.js#L107

One potential fix is to append a character such as `_` or `-` or `.` if the `details` field is too short `if(details.length < 2)`

Below is a line where the `details` field is checked for its length just before posting to Discord RPC, so it seems most fitting to place such a check nearby
https://github.com/vlc-rpc/vlc-discord-rpc/blob/125060006d5baf6b594c71d750a42e453d5a14b7/Functions/rpc-format.js#L191
